stages:
  - build

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/
  - dist/document/

build:
  image: node:latest
  stage: build
  script:
    - git submodule init
    - git submodule update --recursive --remote
    - npm install
    - npm run build
    - ./node_modules/.bin/netlify deploy --prod --dir=dist/ --auth=${netlify_key}