stages:
  - build

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/
  - import-disqus/node_modules/

build:
  image: node:latest
  stage: build
  script:
    - git submodule init
    - git submodule update --recursive --remote
    - npm install
    - npm run build
    - npm --prefix ./import-disqus install ./import-disqus
    - npm --prefix ./import-disqus run build
    - cp -r ./import-disqus/dist ./dist/import-disqus
    - cd ./dist
    - git init
    - git config --global push.default matching
    - git config --global user.email "tcdw2011@gmail.com"
    - git config --global user.name "tcdw"
    - echo 'silverblog.org' > ./CNAME
    - git add --all .
    - DATE="$(echo $(date -Iseconds))"
    - git commit -m "Auto Build via GitLab CI on $DATE"
    - git push --quiet --force "git@github.com:pomment/pomment.github.io.git"
